"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MESSAGE_TYPE = exports.PLAYER_COLORS = void 0;
exports.PLAYER_COLORS = {
    RED: '#FF0000',
    GREEN: '#00FF00',
    BLUE: '#0000FF',
    YELLOW: '#FFFF00',
    PURPLE: '#FF00FF',
    CYAN: '#00FFFF',
    WHITE: '#FFFFFF',
    BLACK: '#000000',
    GRAY: '#8a8a8a',
};
exports.MESSAGE_TYPE = {
    REQUEST_NEW_PAD: 'REQUEST_NEW_PAD',
    REQUEST_ADD_PLAYER: 'REQUEST_ADD_PLAYER',
    REQUEST_UPDATE_PLAYER: 'REQUEST_UPDATE_PLAYER',
    REQUEST_UPDATE_SCORE: 'REQUEST_UPDATE_SCORE',
    REQUEST_JOIN_EXISTING: 'REQUEST_JOIN_EXISTING',
    RESPONSE_MESSAGE: 'RESPONSE_MESSAGE',
    SYSTEM_MESSAGE: 'SYSTEM_MESSAGE',
    REQUEST_LEAVE_EXISTING: 'REQUEST_LEAVE_EXISTING',
    REQUEST_REMOVE_PLAYER: 'REQUEST_REMOVE_PLAYER',
};
