name: Deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3

            - name: Build project
              run: npm run build

            - name: Upload production-ready build files
              uses: actions/upload-artifact@v4
              with:
                  name: production-files
                  path: ./dist

    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: production-files
                  path: ./dist

            - name: Push
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: deploy
                  FOLDER: ./dist
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  MESSAGE: 'Build: ({sha}) {msg}'

            - name: Deploy to DigitalOcean
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  key: ${{ secrets.SSH_KEY }}
                  username: ${{ secrets.SSH_USER }}
                  script: |
                      cd /var/www
                      git clone -b deploy --single-branch https://github.com/JustinHodge/${{ github.event.repository.name }}
